services:
  nuxt-app:
    build: .
    ports:
      - "8374:8374"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NITRO_PORT=8374
      - MONGO_URI=mongodb://mongo:27017/xrpl_commons
      - JWT_SECRET=segredo_super_secreto_xrpl
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: